### ISSUE TITLE
Add `chi_constructor` for perfect entanglers

### ISSUE THREAD

**Issue by goerz** [qucontrol/weylchamber#3]
We need a routine that constructs the chi-states for the perfect entanglers functional. This can be directly adapted from the Fortran code in QDYN.

**Comment by goerz** [comment]
This is definitely better to do in this package... We shouldn't weigh down the `krotov` package with excessive code that is only there for the examples.

Let's add routines `weylchamber.local_invariants.make_LI_krotov_chi_constructor` and `weylchamber.perfect_entanglers.make_PE_krotov_chi_constructor` that return as `chi_constructor` routine for use with Krotov.

Still a prerequisite for https://github.com/qucontrol/krotov/issues/8

**Comment by goerz** [comment]
I created the [`krotov` branch](https://github.com/qucontrol/weylchamber/tree/krotov) for dealing with this. It contains some basic stubs for these routines.

**Comment by goerz** [comment]
@Basilewitsch Can you help with implementing this? Unfortunately, I don't think I'll have too much more time to spend on this in the near future.

**Comment by Basilewitsch** [comment]
Sure, I'll see what I can do!

**Comment by Basilewitsch** [comment]
Maybe @goerz should check the implemented code. It yields identical results with respect to the QDYN implmentation. Apart from possible improvements regarding the documentation, this might even close the issue.

**Comment by goerz** [comment]
Looks pretty good to me. If you've tested that it gives identical results with QDYN, that's probably a good thing to put in a formal test: write the resulting states from QDYN into a file, and then have a test in `weylchamber` that loads the expected amplitudes from that file, calls the `chi_constructor`, and compares.

**Comment by Basilewitsch** [comment]
The latest version of the co-states construction function now takes the unitarity weight into account in the same way as QDYN does. However, I haven't tested it yet with something that actually requires a unitarity weight.

**Comment by goerz** [comment]
Looks good to me.. testing against QDYN should be sufficient.

Closing.
